export const LOADING_STARTED = 'LOADING_STARTED';
export const LOADING_SUCCESSFUL = 'LOADING_SUCCESSFUL';
export const LOADING_FAILED = 'LOADING_FAILED';

export const AUTH_USER = 'AUTH_USER';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const DELETE_FAVOURITES = 'DELETE_FAVOURITES';
export const LOGOUT_USER = 'LOGOUT_USER';

export const EVACUATOR_REQ = 'EVACUATOR_REQ';
export const SHOW_MODAL = 'SHOW_MODAL'

