export const LOADING_STARTED = 'LOADING_STARTED';
export const LOADING_SUCCESSFUL = 'LOADING_SUCCESSFUL';
export const LOADING_FAILED = 'LOADING_FAILED';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
